name: Run Unit Tests

on:
  push:
  pull_request:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes unitários
        run: npm run test
